# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Backlog'), (2, 'Ready'), (3, 'Doing'), (4, 'Blocked'), (5, 'Done')], default=1),
        ),
    ]
